name: Flutter Build & SonarQube

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: '3.32.0' # Includes Dart 3.5.4

      - name: Check Flutter & Dart version
        run: |
          flutter --version
          dart --version

      - name: Clean and Install Dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Build
        run: flutter build apk --debug --android-skip-build-dependency-validation

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
