name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Flutter manually
        run: |
          git clone https://github.com/flutter/flutter.git -b stable
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
          flutter --version
          flutter doctor

      - name: Install dependencies
        run: flutter pub get

      - name: Run analyzer
        run: flutter analyze

      - name: Build debug APK
        run: flutter build apk --debug
